name: CI/CD Pipeline Flask

on:
  push:
    branches:
      - main 
jobs:
  build-and-test: 
    runs-on: ubuntu-latest
    steps:
      - name: Save a value to an environment file
        run: echo "CONTENEDOR=contenedor_dockerflask" >> $GITHUB_ENV

      - name: Save a value to an environment file
        run: echo "IMAGENDOCKERHUB= feliperojas1998/dockerflask:latest" >> $GITHUB_ENV
        
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Install dependencies 
        run: pip install -r Flask/requirements.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 

      - name: Build Docker image
        run: docker buildx build --platform linux/amd64 -t dockerflask Flask/  
        
      - name: Run Docker container
        run: docker run -d --name $CONTENEDOR -p 8080:8080 $IMAGENDOCKERHUB
        
      - name: Test application
        run: docker exec $CONTENEDOR curl -v http://localhost:8080/
       
      
      - name: Check container status
        run: docker ps
                
      
       
        #run: curl http://localhost:8080
      #  run:  docker exec -it $CONTENEDOR curl http://localhost:8080
          
 
      
