name: CI/CD Pipeline Flask

on:
  push:
    branches:
      - main 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Save a value to an environment file
        run: echo "CONTENEDOR=contenedor_dockerflask" >> $GITHUB_ENV

      - name: Save a value to an environment file
        run: echo "IMAGENDOCKERHUB= feliperojas1998/dockerflask:latest" >> $GITHUB_ENV
        
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies 
        run: pip install -r Flask/requirements.txt
      
      #- name: Set up Docker Buildx
       # uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 

      - name: Build Docker image
        run: docker buildx build --platform linux/amd64 -t dockerflask Flask/  


      - name: Run Docker container
      #  run: docker run -d --name contenedor_dockerflask -p 8080:8080 feliperojas1998/dockerflask:latest
        run: docker run -d --name $CONTENEDOR -p 8080:8080 $IMAGENDOCKERHUB
      
      - name: Check container status
        run: docker ps
      

      - name: Test application
        #run: curl http://localhost:8080
        run:  docker exec -it $CONTENEDOR curl http://localhost:8080
      
