name: CI/CD Pipeline Flask

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r Flask/requirements.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t dockerflask Flask/Dockerfile

      - name: Run Docker container
        run: docker run -d --name dockerflask -p 8080:8080 dockerflask

      - name: Deploy to production
        uses: docker/login-action@v1
        
        with:
          provider: GitHub Pages
          target: main
          token: ${{ secrets.GITHUB_TOKEN }}
